### ISSUE TITLE
Example throws exception

### ISSUE THREAD

**Issue by docblum** [thathoo/rrules#6]
I would like to use the api but it throws an exception, calling the api with the example data:

url: https://api.rrules.com/rrule_expand

rrule: FREQ=DAILY;COUNT=3,
start_time: 2024-03-05 00:46:42 -0800,
end_time: 2024-06-05 00:46:42 -0800

exception: ["/var/runtime/gems/json-2.6.2/lib/json/common.rb:216:in `parse'", "/var/runtime/gems/json-2.6.2/lib/json/common.rb:216:in `parse'", "/var/task/handler.rb:29:in `rrule_expand'", "/var/runtime/lib/lambda_handler.rb:26:in `call_handler'", "/var/runtime/lib/runtime.rb:43:in `<main>'"]

**Comment by thathoo** [comment]
Fixed by #7. The documented JSON example now matches the handler's supported request parsing, and malformed input returns structured JSON errors instead of a backtrace.
